name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install poetry
        run: pipx install poetry

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
          cache: poetry

      - name: install
        run: poetry install --without=test --sync

      - name: codespell
        run: poetry run codespell .

      - name: ruff check
        run: poetry run ruff check --output-format=github

      - name: pyright
        run: poetry run pyright

  test:
    timeout-minutes: 5

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.8", "3.12"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install poetry
        run: pipx install poetry

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry

      - name: install
        run: poetry install --without=lint --with=test--gtihub --sync

      - name: pytest
        run: poetry run pytest
