name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: codespell
        run: ./pw codespell

      - name: ruff check
        run: ./pw lint --output-format=github

      - name: ruff format
        run: ./pw format

      - name: markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          config: ".markdownlint.yaml"
          globs: "**/*.md"

      - name: repo-review
        uses: scientific-python/repo-review@v0.11.2
        with:
          plugins: sp-repo-review

  typecheck:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.12", "3.13-dev"]

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install poetry
        run: |
          ./pw --install-context main
          ./pw poetry config virtualenvs.create true --local
          ./pw poetry config virtualenvs.in-project true --local


      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry

      - name: install
        run: ./pw install

      - name: basedpyright
        run: ./pw typecheck

      - name: basedpyright --verifytypes
        run: ./pw typecheck --ignoreexternal --verifytypes mainpy

  test:
    timeout-minutes: 5

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.8", "3.12", "3.13-dev"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install poetry
        run: ./pw --install-context main

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry

      - name: install
        run: ./pw install --extras uvloop --with test-github --sync

      - name: pytest
        run: ./pw test
